### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by PrathamSoni** [fenchri/walk-based-re#3]
These dependencies aren't in the requirements

https://github.com/fenchri/walk-based-re/blob/d02a6b3a7db0582fd21586115050c6c0f0e075d2/data_processing/utils.py#L12-L13

The Genia Tagger also appears to be broken right now.

**Comment by fenchri** [comment]
Hello and thank you for reporting this.

Could you have a look [here](https://github.com/fenchri/edge-oriented-graph#datasets--pre-processing) for a potential solution to the Genia Tagger?
If this works, I will update the readme accordingly.

**Comment by fenchri** [comment]
Could you confirm if this is solved?
